name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅当推送以 v 开头的标签时触发（例如 v1.0.0）
  workflow_dispatch:  # 允许手动触发
    inputs:
      tag_name:
        description: '发布版本标签（例如：v1.0.0）'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20  # 设置较短的超时时间
    strategy:
      fail-fast: false  # 不要因为一个平台失败就停止其他平台
      matrix:
        os: [macos-latest, windows-latest]  # 并行构建 macOS 和 Windows
        include:
          - os: macos-latest
            artifact_name: macos-binary
          - os: windows-latest
            artifact_name: windows-binary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，避免浅克隆问题

      - name: Configure Git (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # 降级到 Node 18，更稳定
          cache: 'yarn'

      - name: Setup Build Environment
        run: |
          echo "Setting up build environment..."
          node --version
          npm --version
          yarn --version
        shell: bash

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          yarn install --network-timeout 300000
        shell: bash

      - name: Build TypeScript
        run: |
          echo "Building TypeScript..."
          yarn build
        shell: bash

      - name: Build Native Module
        run: |
          echo "Building native module..."
          yarn rebuild
        shell: bash
        continue-on-error: false

      - name: Verify Build Output
        run: |
          echo "Checking build output..."
          ls -la dist/ || echo "No dist directory"
          ls -la build/ || echo "No build directory"
        shell: bash

      - name: Archive Artifacts
        run: |
          echo "Creating release package..."
          mkdir -p release-package
          
          # 复制必要文件
          if [ -d "dist" ]; then
            cp -r dist release-package/
            echo "Copied dist directory"
          fi
          
          if [ -d "build" ]; then
            cp -r build release-package/
            echo "Copied build directory"
          fi
          
          cp package.json release-package/
          cp README.md release-package/
          cp LICENSE release-package/
          
          # 创建压缩包
          cd release-package
          tar -czf ../${{ matrix.artifact_name }}.tar.gz .
          cd ..
          
          echo "Archive created: ${{ matrix.artifact_name }}.tar.gz"
          ls -la ${{ matrix.artifact_name }}.tar.gz
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz

  release:
    needs: build  # 依赖 build 任务
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间
    if: ${{ !cancelled() && (needs.build.result == 'success' || needs.build.result == 'failure') }}  # 即使部分构建失败也继续
    permissions:
      contents: write  # 允许创建 Release

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
        continue-on-error: true

      - name: List Available Artifacts
        run: |
          echo "Available artifacts:"
          find ./artifacts -type f -name "*.tar.gz" || echo "No artifacts found"
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}  # 手动触发时使用输入的标签，自动触发时使用推送的标签
          name: Release ${{ inputs.tag_name || github.ref_name }}
          files: |
            artifacts/*/*.tar.gz
          draft: false
          fail_on_unmatched_files: false  # 不要因为找不到文件而失败
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置 Token