name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅当推送以 v 开头的标签时触发（例如 v1.0.0）
  workflow_dispatch:  # 允许手动触发
    inputs:
      tag_name:
        description: '发布版本标签（例如：v1.0.0）'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20  # 设置较短的超时时间
    strategy:
      fail-fast: false  # 不要因为一个平台失败就停止其他平台
      matrix:
        os: [macos-latest, windows-latest]  # 并行构建 macOS 和 Windows
        include:
          - os: macos-latest
            artifact_name: macos-binary
          - os: windows-latest
            artifact_name: windows-binary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，避免浅克隆问题

      - name: Configure Git (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 使用 Python 3.10，兼容 node-gyp

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # 降级到 Node 18，更稳定
          cache: 'yarn'
          architecture: 'x64'  # 明确指定 x64 架构

      - name: Add MSBuild to PATH (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2

      - name: Setup Windows Build Environment
        if: matrix.os == 'windows-latest'
        run: |
          # 强制设置架构为 x64
          echo "npm_config_target_arch=x64" >> $GITHUB_ENV
          echo "npm_config_target_platform=win32" >> $GITHUB_ENV
          echo "npm_config_arch=x64" >> $GITHUB_ENV
          echo "npm_config_node_gyp_force_arch=x64" >> $GITHUB_ENV
          
          # 设置 node-gyp 环境变量，不指定特定版本
          echo "npm_config_node_gyp_force_python=python" >> $GITHUB_ENV
          
          # 清除可能导致问题的环境变量
          echo "npm_config_msvs_version=" >> $GITHUB_ENV
        shell: bash

      - name: Setup Build Environment
        run: |
          echo "Setting up build environment..."
          python --version
          node --version
          npm --version
          yarn --version
          
          # macOS 特定设置
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "Setting up macOS build environment..."
            # 确保有 Xcode 命令行工具
            xcode-select --print-path
            # 设置 CC 和 CXX 环境变量
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
          
          # Windows 特定设置
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Setting up Windows build environment..."
            # 设置全局环境变量用于 node-gyp
            echo "PYTHON=python" >> $GITHUB_ENV
            echo "npm_config_python=python" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Setup Windows Build Tools
        if: matrix.os == 'windows-latest'
        run: |
          echo "Setting up Windows build tools..."
          
          # 检查 Python 安装
          echo "Python version:"
          python --version
          
          # 检查架构设置
          echo "Architecture configuration:"
          echo "npm_config_target_arch: $npm_config_target_arch"
          echo "npm_config_arch: $npm_config_arch"
          echo "npm_config_target_platform: $npm_config_target_platform"
          
          # 安装必要的工具
          npm install -g @mapbox/node-pre-gyp
          echo "Build tools setup complete"
        shell: bash

      - name: Update node-gyp
        run: |
          echo "Updating node-gyp to latest version..."
          npm install -g node-gyp@latest
          node-gyp --version
        shell: bash

      - name: Clean Build Cache
        run: |
          echo "Cleaning build cache..."
          # 清理 node-gyp 缓存
          node-gyp clean || true
          # 清理 npm 缓存
          npm cache clean --force
        shell: bash

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          yarn install --network-timeout 300000
        shell: bash
        env:
          PYTHON: python
          npm_config_python: python

      - name: Build TypeScript
        run: |
          echo "Building TypeScript..."
          yarn build
        shell: bash

      - name: Build Native Module
        run: |
          echo "Building native module for ${{ matrix.os }}..."
          
          # Windows 特殊处理 - 强制使用 x64 架构
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Setting up Windows build environment..."
            export npm_config_target_arch=x64
            export npm_config_arch=x64
            export npm_config_target_platform=win32
            
            # 显示当前环境变量
            echo "Architecture settings:"
            echo "npm_config_target_arch: $npm_config_target_arch"
            echo "npm_config_arch: $npm_config_arch"
          fi
          
          yarn rebuild
          
          # 创建预编译二进制文件夹结构
          echo "Creating prebuilt binary structure..."
          mkdir -p prebuilds
          
          # 复制编译好的二进制文件
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            mkdir -p "prebuilds/darwin-x64"
            if [ -f "build/Release/addon.node" ]; then
              cp "build/Release/addon.node" "prebuilds/darwin-x64/"
            fi
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            mkdir -p "prebuilds/win32-x64"
            if [ -f "build/Release/addon.node" ]; then
              cp "build/Release/addon.node" "prebuilds/win32-x64/"
            fi
          fi
          
          echo "Build output:"
          ls -la build/Release/ || echo "No build output found"
        shell: bash
        env:
          PYTHON: python
          npm_config_python: python
        continue-on-error: false

      - name: Verify Build Output
        run: |
          echo "Checking build output..."
          ls -la dist/ || echo "No dist directory"
          ls -la build/ || echo "No build directory"
          ls -la prebuilds/ || echo "No prebuilds directory"
          
          # 显示预编译二进制文件
          if [ -d "prebuilds" ]; then
            echo "Prebuilt binaries:"
            find prebuilds -name "*.node" -exec ls -la {} \;
          fi
        shell: bash

      - name: Archive Artifacts
        run: |
          echo "Creating release package..."
          mkdir -p release-package
          
          # 复制必要文件
          if [ -d "dist" ]; then
            cp -r dist release-package/
            echo "Copied dist directory"
          fi
          
          if [ -d "build" ]; then
            cp -r build release-package/
            echo "Copied build directory"
          fi
          
          if [ -d "prebuilds" ]; then
            cp -r prebuilds release-package/
            echo "Copied prebuilds directory"
          fi
          
          # 复制其他必要文件
          cp package.json release-package/
          cp README.md release-package/
          cp LICENSE release-package/
          cp binding.gyp release-package/
          
          # 创建压缩包
          cd release-package
          tar -czf ../${{ matrix.artifact_name }}.tar.gz .
          cd ..
          
          echo "Archive created: ${{ matrix.artifact_name }}.tar.gz"
          ls -la ${{ matrix.artifact_name }}.tar.gz
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz

  release:
    needs: build  # 依赖 build 任务
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间
    if: ${{ !cancelled() && (needs.build.result == 'success' || needs.build.result == 'failure') }}  # 即使部分构建失败也继续
    permissions:
      contents: write  # 允许创建 Release

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
        continue-on-error: true

      - name: List Available Artifacts
        run: |
          echo "Available artifacts:"
          find ./artifacts -type f -name "*.tar.gz" || echo "No artifacts found"
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}  # 手动触发时使用输入的标签，自动触发时使用推送的标签
          name: Release ${{ inputs.tag_name || github.ref_name }}
          files: |
            artifacts/*/*.tar.gz
          draft: false
          fail_on_unmatched_files: false  # 不要因为找不到文件而失败
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置 Token